package com.netease.miniadmin.model;

import java.util.Date;

public class ConditionTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column condition_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column condition_tag.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column condition_tag.condition_tag_name
     *
     * @mbggenerated
     */
    private String conditionTagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column condition_tag.condition_tag_id
     *
     * @mbggenerated
     */
    private Integer conditionTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column condition_tag.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column condition_tag.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column condition_tag.id
     *
     * @return the value of condition_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column condition_tag.id
     *
     * @param id the value for condition_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column condition_tag.open_id
     *
     * @return the value of condition_tag.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column condition_tag.open_id
     *
     * @param openId the value for condition_tag.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column condition_tag.condition_tag_name
     *
     * @return the value of condition_tag.condition_tag_name
     *
     * @mbggenerated
     */
    public String getConditionTagName() {
        return conditionTagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column condition_tag.condition_tag_name
     *
     * @param conditionTagName the value for condition_tag.condition_tag_name
     *
     * @mbggenerated
     */
    public void setConditionTagName(String conditionTagName) {
        this.conditionTagName = conditionTagName == null ? null : conditionTagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column condition_tag.condition_tag_id
     *
     * @return the value of condition_tag.condition_tag_id
     *
     * @mbggenerated
     */
    public Integer getConditionTagId() {
        return conditionTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column condition_tag.condition_tag_id
     *
     * @param conditionTagId the value for condition_tag.condition_tag_id
     *
     * @mbggenerated
     */
    public void setConditionTagId(Integer conditionTagId) {
        this.conditionTagId = conditionTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column condition_tag.create_time
     *
     * @return the value of condition_tag.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column condition_tag.create_time
     *
     * @param createTime the value for condition_tag.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column condition_tag.modify_time
     *
     * @return the value of condition_tag.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column condition_tag.modify_time
     *
     * @param modifyTime the value for condition_tag.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}