package com.netease.miniadmin.model;

import java.util.Date;

public class Dynamics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.diary
     *
     * @mbggenerated
     */
    private String diary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.emotion_rate
     *
     * @mbggenerated
     */
    private Integer emotionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.secret
     *
     * @mbggenerated
     */
    private Integer secret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamics.poster
     *
     * @mbggenerated
     */
    private String poster;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.id
     *
     * @return the value of dynamics.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.id
     *
     * @param id the value for dynamics.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.open_id
     *
     * @return the value of dynamics.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.open_id
     *
     * @param openId the value for dynamics.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.diary
     *
     * @return the value of dynamics.diary
     *
     * @mbggenerated
     */
    public String getDiary() {
        return diary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.diary
     *
     * @param diary the value for dynamics.diary
     *
     * @mbggenerated
     */
    public void setDiary(String diary) {
        this.diary = diary == null ? null : diary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.create_time
     *
     * @return the value of dynamics.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.create_time
     *
     * @param createTime the value for dynamics.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.emotion_rate
     *
     * @return the value of dynamics.emotion_rate
     *
     * @mbggenerated
     */
    public Integer getEmotionRate() {
        return emotionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.emotion_rate
     *
     * @param emotionRate the value for dynamics.emotion_rate
     *
     * @mbggenerated
     */
    public void setEmotionRate(Integer emotionRate) {
        this.emotionRate = emotionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.secret
     *
     * @return the value of dynamics.secret
     *
     * @mbggenerated
     */
    public Integer getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.secret
     *
     * @param secret the value for dynamics.secret
     *
     * @mbggenerated
     */
    public void setSecret(Integer secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.modify_time
     *
     * @return the value of dynamics.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.modify_time
     *
     * @param modifyTime the value for dynamics.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.location
     *
     * @return the value of dynamics.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.location
     *
     * @param location the value for dynamics.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamics.poster
     *
     * @return the value of dynamics.poster
     *
     * @mbggenerated
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamics.poster
     *
     * @param poster the value for dynamics.poster
     *
     * @mbggenerated
     */
    public void setPoster(String poster) {
        this.poster = poster == null ? null : poster.trim();
    }
}