package com.netease.miniadmin.model;

import java.util.Date;

public class MatchResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.user_open_id
     *
     * @mbggenerated
     */
    private String userOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.user_avatar_url
     *
     * @mbggenerated
     */
    private String userAvatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.target_nick_name
     *
     * @mbggenerated
     */
    private String targetNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.target_avatar_url
     *
     * @mbggenerated
     */
    private String targetAvatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.target_open_id
     *
     * @mbggenerated
     */
    private String targetOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.match_tags
     *
     * @mbggenerated
     */
    private String matchTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_result.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.id
     *
     * @return the value of match_result.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.id
     *
     * @param id the value for match_result.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.user_open_id
     *
     * @return the value of match_result.user_open_id
     *
     * @mbggenerated
     */
    public String getUserOpenId() {
        return userOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.user_open_id
     *
     * @param userOpenId the value for match_result.user_open_id
     *
     * @mbggenerated
     */
    public void setUserOpenId(String userOpenId) {
        this.userOpenId = userOpenId == null ? null : userOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.user_avatar_url
     *
     * @return the value of match_result.user_avatar_url
     *
     * @mbggenerated
     */
    public String getUserAvatarUrl() {
        return userAvatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.user_avatar_url
     *
     * @param userAvatarUrl the value for match_result.user_avatar_url
     *
     * @mbggenerated
     */
    public void setUserAvatarUrl(String userAvatarUrl) {
        this.userAvatarUrl = userAvatarUrl == null ? null : userAvatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.target_nick_name
     *
     * @return the value of match_result.target_nick_name
     *
     * @mbggenerated
     */
    public String getTargetNickName() {
        return targetNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.target_nick_name
     *
     * @param targetNickName the value for match_result.target_nick_name
     *
     * @mbggenerated
     */
    public void setTargetNickName(String targetNickName) {
        this.targetNickName = targetNickName == null ? null : targetNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.target_avatar_url
     *
     * @return the value of match_result.target_avatar_url
     *
     * @mbggenerated
     */
    public String getTargetAvatarUrl() {
        return targetAvatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.target_avatar_url
     *
     * @param targetAvatarUrl the value for match_result.target_avatar_url
     *
     * @mbggenerated
     */
    public void setTargetAvatarUrl(String targetAvatarUrl) {
        this.targetAvatarUrl = targetAvatarUrl == null ? null : targetAvatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.target_open_id
     *
     * @return the value of match_result.target_open_id
     *
     * @mbggenerated
     */
    public String getTargetOpenId() {
        return targetOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.target_open_id
     *
     * @param targetOpenId the value for match_result.target_open_id
     *
     * @mbggenerated
     */
    public void setTargetOpenId(String targetOpenId) {
        this.targetOpenId = targetOpenId == null ? null : targetOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.group_id
     *
     * @return the value of match_result.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.group_id
     *
     * @param groupId the value for match_result.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.group_name
     *
     * @return the value of match_result.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.group_name
     *
     * @param groupName the value for match_result.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.match_tags
     *
     * @return the value of match_result.match_tags
     *
     * @mbggenerated
     */
    public String getMatchTags() {
        return matchTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.match_tags
     *
     * @param matchTags the value for match_result.match_tags
     *
     * @mbggenerated
     */
    public void setMatchTags(String matchTags) {
        this.matchTags = matchTags == null ? null : matchTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.create_time
     *
     * @return the value of match_result.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.create_time
     *
     * @param createTime the value for match_result.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_result.modify_time
     *
     * @return the value of match_result.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_result.modify_time
     *
     * @param modifyTime the value for match_result.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}