package com.netease.miniadmin.model;

import java.util.Date;

public class SpecialRequirement extends SpecialRequirementKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.height_min
     *
     * @mbggenerated
     */
    private Integer heightMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.height_max
     *
     * @mbggenerated
     */
    private Integer heightMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.weight_min
     *
     * @mbggenerated
     */
    private Integer weightMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.weight_max
     *
     * @mbggenerated
     */
    private Integer weightMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.hometown_city
     *
     * @mbggenerated
     */
    private String hometownCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.hometown_province
     *
     * @mbggenerated
     */
    private String hometownProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.constellation
     *
     * @mbggenerated
     */
    private String constellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.degree
     *
     * @mbggenerated
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.work_status
     *
     * @mbggenerated
     */
    private Integer workStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.age_min
     *
     * @mbggenerated
     */
    private Integer ageMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.age_max
     *
     * @mbggenerated
     */
    private Integer ageMax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.height_min
     *
     * @return the value of special_requirement.height_min
     *
     * @mbggenerated
     */
    public Integer getHeightMin() {
        return heightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.height_min
     *
     * @param heightMin the value for special_requirement.height_min
     *
     * @mbggenerated
     */
    public void setHeightMin(Integer heightMin) {
        this.heightMin = heightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.height_max
     *
     * @return the value of special_requirement.height_max
     *
     * @mbggenerated
     */
    public Integer getHeightMax() {
        return heightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.height_max
     *
     * @param heightMax the value for special_requirement.height_max
     *
     * @mbggenerated
     */
    public void setHeightMax(Integer heightMax) {
        this.heightMax = heightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.weight_min
     *
     * @return the value of special_requirement.weight_min
     *
     * @mbggenerated
     */
    public Integer getWeightMin() {
        return weightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.weight_min
     *
     * @param weightMin the value for special_requirement.weight_min
     *
     * @mbggenerated
     */
    public void setWeightMin(Integer weightMin) {
        this.weightMin = weightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.weight_max
     *
     * @return the value of special_requirement.weight_max
     *
     * @mbggenerated
     */
    public Integer getWeightMax() {
        return weightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.weight_max
     *
     * @param weightMax the value for special_requirement.weight_max
     *
     * @mbggenerated
     */
    public void setWeightMax(Integer weightMax) {
        this.weightMax = weightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.school
     *
     * @return the value of special_requirement.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.school
     *
     * @param school the value for special_requirement.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.city
     *
     * @return the value of special_requirement.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.city
     *
     * @param city the value for special_requirement.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.create_time
     *
     * @return the value of special_requirement.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.create_time
     *
     * @param createTime the value for special_requirement.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.modify_time
     *
     * @return the value of special_requirement.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.modify_time
     *
     * @param modifyTime the value for special_requirement.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.hometown_city
     *
     * @return the value of special_requirement.hometown_city
     *
     * @mbggenerated
     */
    public String getHometownCity() {
        return hometownCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.hometown_city
     *
     * @param hometownCity the value for special_requirement.hometown_city
     *
     * @mbggenerated
     */
    public void setHometownCity(String hometownCity) {
        this.hometownCity = hometownCity == null ? null : hometownCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.hometown_province
     *
     * @return the value of special_requirement.hometown_province
     *
     * @mbggenerated
     */
    public String getHometownProvince() {
        return hometownProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.hometown_province
     *
     * @param hometownProvince the value for special_requirement.hometown_province
     *
     * @mbggenerated
     */
    public void setHometownProvince(String hometownProvince) {
        this.hometownProvince = hometownProvince == null ? null : hometownProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.province
     *
     * @return the value of special_requirement.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.province
     *
     * @param province the value for special_requirement.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.constellation
     *
     * @return the value of special_requirement.constellation
     *
     * @mbggenerated
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.constellation
     *
     * @param constellation the value for special_requirement.constellation
     *
     * @mbggenerated
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation == null ? null : constellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.degree
     *
     * @return the value of special_requirement.degree
     *
     * @mbggenerated
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.degree
     *
     * @param degree the value for special_requirement.degree
     *
     * @mbggenerated
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.work_status
     *
     * @return the value of special_requirement.work_status
     *
     * @mbggenerated
     */
    public Integer getWorkStatus() {
        return workStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.work_status
     *
     * @param workStatus the value for special_requirement.work_status
     *
     * @mbggenerated
     */
    public void setWorkStatus(Integer workStatus) {
        this.workStatus = workStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.age_min
     *
     * @return the value of special_requirement.age_min
     *
     * @mbggenerated
     */
    public Integer getAgeMin() {
        return ageMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.age_min
     *
     * @param ageMin the value for special_requirement.age_min
     *
     * @mbggenerated
     */
    public void setAgeMin(Integer ageMin) {
        this.ageMin = ageMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.age_max
     *
     * @return the value of special_requirement.age_max
     *
     * @mbggenerated
     */
    public Integer getAgeMax() {
        return ageMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.age_max
     *
     * @param ageMax the value for special_requirement.age_max
     *
     * @mbggenerated
     */
    public void setAgeMax(Integer ageMax) {
        this.ageMax = ageMax;
    }
}