package com.netease.miniadmin.model;

public class SpecialRequirementKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_requirement.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.id
     *
     * @return the value of special_requirement.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.id
     *
     * @param id the value for special_requirement.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_requirement.open_id
     *
     * @return the value of special_requirement.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_requirement.open_id
     *
     * @param openId the value for special_requirement.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }
}