package com.netease.miniadmin.model;

public class UserWithBLOBs extends User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbggenerated
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upload_avatar_url
     *
     * @mbggenerated
     */
    private String uploadAvatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbggenerated
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbggenerated
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upload_avatar_url
     *
     * @return the value of user.upload_avatar_url
     *
     * @mbggenerated
     */
    public String getUploadAvatarUrl() {
        return uploadAvatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upload_avatar_url
     *
     * @param uploadAvatarUrl the value for user.upload_avatar_url
     *
     * @mbggenerated
     */
    public void setUploadAvatarUrl(String uploadAvatarUrl) {
        this.uploadAvatarUrl = uploadAvatarUrl == null ? null : uploadAvatarUrl.trim();
    }
}