package com.netease.miniadmin.mapper;

import com.netease.miniadmin.model.DynamicsTemplate;

public interface DynamicsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics_template
     *
     * @mbggenerated
     */
    int insert(DynamicsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics_template
     *
     * @mbggenerated
     */
    int insertSelective(DynamicsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics_template
     *
     * @mbggenerated
     */
    DynamicsTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DynamicsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DynamicsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DynamicsTemplate record);
}