package com.netease.miniadmin.mapper;

import com.netease.miniadmin.dto.CountResultDto;
import com.netease.miniadmin.model.Dynamics;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface DynamicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics
     *
     * @mbggenerated
     */
    int insert(Dynamics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics
     *
     * @mbggenerated
     */
    int insertSelective(Dynamics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics
     *
     * @mbggenerated
     */
    Dynamics selectByPrimaryKey(Integer id);

    /**
     * 此方法用于返回每个用户的动态数目。
     * @return
     */
    List<CountResultDto> selectDynamicsNum();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dynamics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Dynamics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dynamics record);
}