package com.netease.miniadmin.mapper;

import com.netease.miniadmin.model.GroupRelation;

public interface GroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int insert(GroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int insertSelective(GroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    GroupRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupRelation record);
}