package com.netease.miniadmin.mapper;

import com.netease.miniadmin.dto.CountResultDto;
import com.netease.miniadmin.model.GroupRelation;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface GroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int insert(GroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int insertSelective(GroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    GroupRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupRelation record);

    /**
     * 获取用户参与匹配的群数目
     * @return
     */
    List<CountResultDto> getUserMathchGroupNum();
}