package com.netease.miniadmin.mapper;

import com.netease.miniadmin.model.MatchResult;

public interface MatchResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbggenerated
     */
    int insert(MatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbggenerated
     */
    int insertSelective(MatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbggenerated
     */
    MatchResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MatchResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MatchResult record);
}