package com.netease.miniadmin.mapper;

import com.netease.miniadmin.model.RequirementTag;

public interface RequirementTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int insert(RequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int insertSelective(RequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    RequirementTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RequirementTag record);
}