package com.netease.miniadmin.mapper;

import com.netease.miniadmin.dto.CountResult;
import com.netease.miniadmin.model.RequirementTag;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
@Component
public interface RequirementTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int insert(RequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int insertSelective(RequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    RequirementTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RequirementTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RequirementTag record);

    /**
     * 查询每一个需求标签被选择的次数
     * @return
     */
    List<CountResult> selectEveryRequireTagCount();
}