package com.netease.miniadmin.mapper;

import com.netease.miniadmin.model.SpecialRequirement;
import com.netease.miniadmin.model.SpecialRequirementKey;

public interface SpecialRequirementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_requirement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SpecialRequirementKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_requirement
     *
     * @mbggenerated
     */
    int insert(SpecialRequirement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_requirement
     *
     * @mbggenerated
     */
    int insertSelective(SpecialRequirement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_requirement
     *
     * @mbggenerated
     */
    SpecialRequirement selectByPrimaryKey(SpecialRequirementKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_requirement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialRequirement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_requirement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialRequirement record);
}