package com.netease.miniadmin.mapper;

import com.netease.miniadmin.model.PageQuery;
import com.netease.miniadmin.model.UserFeedback;

import java.util.List;

public interface UserFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated
     */
    int insert(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated
     */
    int insertSelective(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated
     */
    UserFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserFeedback record);

    /**
     * 分页查询
     * @return
     */
    List<UserFeedback> pageQuery();
}